version: '3.7'

services:
  telegram-gateway:
    build: .
    restart: always
    ports:
      - "231:8000"
    networks:
      default: null

networks:
  default:
    external: true
    name: classifier
